### ISSUE TITLE
Only works on a single connection...

### ISSUE THREAD

**Issue by ImCarsen** [nabrezzelt/MessageSystemCS#1]
Like every other tutorial, source code and so on, this only works on one connection, so you can only use it on LAN. What is the point? there is not use for this, it does not help, the point of a chat application is so you can instantly message someone who is too far to hear you speak to them. If you can (I know this was made in 2017) find a way to do this, but on different connections.

**Comment by nabrezzelt** [comment]
What do you mean with different connections?

If you want to use it outside of you LAN just run it on a server in the Internet and set the dns/ip in your clients.
